name: Django CI

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python Local
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies Local
      run: |
        pip install -r requirements.txt

    - name: Run Tests Local
      run: |
        cd src/
        python manage.py test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker Image
      run: |
        docker-compose build

    - name: Run Tests with Docker
      run: |
        docker-compose run --rm web python manage.py test
