name: Django CI Dev

on:
  push:
    branches:
      - dev_test
  pull_request:
    branches:
      - dev_test

jobs:
  test-local:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 1
    environment: dev

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Setup Django Secret Key
      run: |
        MY_GEN_KEY=$(openssl rand -base64 32)
        echo "DJANGO_SECRET_KEY=$MY_GEN_KEY" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt

    - name: Run Tests (Local)
      run: |
        cd src/
        python manage.py test
