name: Django CI Homolog

on:
  push:
    branches:
      - dev_test
  pull_request:
    branches:
      - dev_test

jobs:

  test-local:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests (Local)
      run: |
        cd src/
        python manage.py test

  test-docker:
    runs-on: ubuntu-latest
    needs: test-local
    environment: homolog

    steps:
    - uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: |
        docker-compose build

    - name: Run Tests with Docker
      run: |
        docker-compose run --rm web python manage.py test
