name: Django CI Homolog - Docker

on:
  # push:
  #   branches:
  #     - dev_test
  pull_request:
    branches:
      - main

jobs:

  test-docker:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: ${{ vars.DJANGO_DEBUG }}
      ORACLE_DATABASE_URL: ${{ vars.ORACLE_DATABASE_URL }}

      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      ORACLE_USER: ${{ secrets.ORACLE_USER }}
      ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
      ORACLE_DSN: ${{ secrets.ORACLE_DSN }}
    environment: homolog

    steps:
    - uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: |
        docker-compose build

    - name: Run Tests with Docker
      run: |
        chmod +x $SCRIPT_NAME
        docker-compose run --rm web $SCRIPT_NAME